### PR TITLE
#28: High level pattern player API

### PR DESCRIPTION
**Pull request by jhannes**
A first stab at #28.

Notes:
- I found it difficult to approach the timing logic in combination with `unit-tests.js`, so I only added a `test-sequence.js` "manual" test instead
- Supports tinycolor2 to use color names. Adds function `fadeToColor` which uses tinycolor
- Implemented using the setTimeout mechanism in `fadeToRGB`
- When I tried to implement using `writePatternLine` and `play`, more colors than those I had specified where displayed!

### CODE REVIEW

**Comment by sandeepmistry** [comment]
Hi @jhannes,

Thanks for taking the time to submit this pull request!

To continue the discussion from #28, I just tried the following to get a loop playing without any setTimeout on the JS side.

```js
var Blink1 = require('./blink1');

var blink1 = new Blink1();

blink1.writePatternLine(1000, 255, 0, 0, 0); // one second, read, position 0
blink1.writePatternLine(1000, 0, 255, 0, 1); // one second, green, position 1
blink1.writePatternLine(1000, 0, 0, 255, 2); // one seconnd, blue, position 2

blink1.playLoop(0, 2, 0); // start position 0, end position 2, 0 => loop forever
```

Do you mind trying it out? You should see a loop of `red -> green -> blue` with 1 second fade between. Hopefully this clarifies `writePatternLine` + `playLoop` usage.

cc/ @todbot

**Comment by jhannes** [comment]
@sandeepmistry I tried the code you provided and it doesn't give the expected behavior. Instead it blinks white, green, purple, cyan, green, red and many more.

NB: I have an old blink1 - purchased during the kickstarter days. Could this be the problem?

/cc @todbot

**Comment by sandeepmistry** [comment]
Here's a video of what I see on my mk2, I expect the original blink1 to be the same. I haven't tried it yet.

[IMG_1262-480.zip](https://github.com/sandeepmistry/node-blink1/files/505172/IMG_1262-480.zip)

**Comment by jhannes** [comment]
@sandeepmistry It looks to me like your blink1 is cycling through a lot of colors. Was this based on the 3 pattern lines you wrote in the example? Then it's similar to mine.

Is this correct? (as in, did the blink1 do what one should expect it to do?)

(I can't record a video as I forgot my blink1 at the project I just left!)

**Comment by sandeepmistry** [comment]
I think I understand, you don't want the long fades (red -> yellow -> green), but instead you want to switch right away. Try this out:

```javascript
var Blink1 = require('./blink1');

var blink1 = new Blink1();

blink1.writePatternLine(10, 255, 0, 0, 0); // fade to red quickly
blink1.writePatternLine(1000, 255, 0, 0, 1); // stay red for 1s


blink1.writePatternLine(10, 0, 255, 0, 2); // fade to green quickly
blink1.writePatternLine(1000, 0, 255, 0, 3); // stay green for 1s

blink1.writePatternLine(10, 0, 0, 255, 4); // fade to blue quickly
blink1.writePatternLine(1000, 0, 0, 255, 5); // stay blue for 1s

blink1.playLoop(0, 5, 0); // start position 0, end position 5, 0 => loop forever
```

**Comment by sandeepmistry** [comment]
@todbot 

> the writePatternLine() methods (and similar pattern & loop methods that issues HID reports to the blink(1) hardware) should not be used if you're building and playing patterns to be used in real-time in Node. 

Any reason specifically? If you just want to blink something from Node, `setTimeout` seems a bit overkill, especially if we can offload the logic to the blink(1) ...

**Comment by jhannes** [comment]
Looks like we're getting somewhere good. :-)

To @todbot's points:

- Actually, my example supports varying step times. For example `var pattern = [{color: "black", delay: 1000}, "red", {color: "white", delay: 1000}, "yellow"];`. I'm not certain that supporting flexible parameters like this is always a good idea, though.
- I didn't know what the ledn parameter was at the time, but I'll look into this next
- I agree that cluttering up the blink1 class with too much stuff is a risk. The reverse risk is that of reduced discoverability of the API. I think that in this case, we're better of erring on the side of putting too much together rather than splitting up, but I may be wrong.
- The `fadeScale` looks interesting, but I'm not sure it's the best abstraction. I think this was what I tried to do with this example `var pattern = ["black", "red", "red", "black"];` (the double red is for a hold). What about `fadeTime` and `holdTime` instead? E.g. `[{color: 'off', fadeTime: 200, holdTime:  200}, {color: 'red', fadeTime: 200, holdTime: 1000}]`

**Comment by sandeepmistry** [comment]
@todbot thanks for the explanation about reasons no to use pattern lines! The EEPROM one is the biggest turn off for me.

> Cluttering up the node-blink1 base class seemed unaesthetic to me, so I pulled all the pattern stuff to a different class. (Though this is purely a code style choice)

I'm leaning towards have a new `Blink1Animator` or `Blink1Animation` class, not attached to the names, so open to suggestions. It can have handle all the fancy timer stuff and use the current API's for the lower level.

@jhannes  @todbot What do you think?

> I agree that cluttering up the blink1 class with too much stuff is a risk. The reverse risk is that of reduced discoverability of the API. I think that in this case, we're better of erring on the side of putting too much together rather than splitting up, but I may be wrong.

I'm not too concerned about this, we can add some new examples to improve discovery and the API docs. From my experience, examples are used more, the API's docs are read less often.

**Comment by sandeepmistry** [comment]
Closing this for now due to lack of activity ...

**Pull request closed without merging**
